import type { Metadata } from "next";
import "../styles/globals.css"
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Scalable app",
  description: "Generated by Frontend web",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Navbar />
        <div className="flex max-w-[1440px] mx-auto">
          <Sidebar />
          <main className="ml-[300px] flex-1 mt-[90px] mb-[32px] min-h-screen border-1 border-[red] overflow-y-auto no-scrollbar px-12">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

//  ml-[300px]
