import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "../components/Navbar";
import SidebarWrapper from "@/components/SidebarWrapper";

export const metadata: Metadata = {
  title: "Scalable app",
  description: "Generated by Frontend web",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Navbar />
        <div className="w-[80%] max-w-[1440px] mx-auto">
          <SidebarWrapper>{children}</SidebarWrapper>
        </div>
      </body>
    </html>
  );
}
